export const audioMap = {
  "Ready to crack the code in every table?": "/assets/audio/391c2f65.mp3",
  "Hmm... I wonder...": "/assets/audio/665535de.mp3",
  "Which bus should Emma take to reach school by 7:45 am?": "/assets/audio/23db8739.mp3",
  "What if two buses arrive at the same time?": "/assets/audio/7e5598e8.mp3",
  "We might need to compare more than one column!": "/assets/audio/63b6d754.mp3",
  "Let's investigate!": "/assets/audio/da872c5.mp3",
  "Leo is planning a fun weekend. He looks at the weather table.": "/assets/audio/ae740bb.mp3",
  "He wants to go to the park, but he needs to find a sunny day.": "/assets/audio/32d9b11c.mp3",
  "Which day has the highest temperature and no rain?": "/assets/audio/1d63bbc7.mp3",
  "Let's help Leo read the weather table!": "/assets/audio/338dc9d8.mp3",
  "Click any row to reveal a summary of that row's data.": "/assets/audio/24c7389f.mp3",
  "Click any column header to highlight that column across all rows.": "/assets/audio/6c17521e.mp3",
  "Use the slider to select a row and a column simultaneously.": "/assets/audio/2ac92681.mp3",
  "Tap the incorrect cell in the table to fix the mismatch.": "/assets/audio/5c91ad9a.mp3",
  "Cross-check needed!": "/assets/audio/4e7976f9.mp3",
  "Great job spotting the error!": "/assets/audio/6ba648be.mp3",
  "Row 1: On Monday, it is 28°C and rain is No.": "/assets/audio/3bc74788.mp3",
  "Row 2: On Tuesday, it is 30°C and rain is Yes.": "/assets/audio/38c7fbb7.mp3",
  "Row 3: On Wednesday, it is 33°C and rain is No.": "/assets/audio/2f0b7b6.mp3",
  "Player Column: Lists all the students participating.": "/assets/audio/125799d9.mp3",
  "Points Column: Total points = 360.": "/assets/audio/1b2bd8b4.mp3",
  "Rank Column: Lowest number means 1st place!": "/assets/audio/4e1439b3.mp3",
  "Journey Complete!": "/assets/audio/57e17968.mp3",
  "Amazing! You've mastered reading tables.": "/assets/audio/eb75fe3.mp3",
  "Play Again": "/assets/audio/7b558774.mp3",
  "Next": "/assets/audio/24ff13.mp3",
  "Back": "/assets/audio/1f7907.mp3",
  "That's right, keep it up!": "/assets/audio/6ca9d117.mp3",
  "Not quite, try it in next questions.": "/assets/audio/46372666.mp3",
  "Question 1. Let's look at the Weather Watch table. What is the value in row 1 and column 2?": "/assets/audio/7bdcf69c.mp3",
  "Question 2. Let's look at the Weather Watch table. What is the value in row 2 and column 2?": "/assets/audio/469cafc.mp3",
  "Question 3. Let's look at the Weather Watch table. What is the value in row 3 and column 2?": "/assets/audio/730960a4.mp3",
  "Question 4. Let's look at the Weather Watch table. Which row has the highest value?": "/assets/audio/714ab2f5.mp3",
  "Question 5. Let's look at the Weather Watch table. Which row has the highest value?": "/assets/audio/56d9b9d6.mp3",
  "Question 6. Let's look at the Weather Watch table. Which row has the highest value?": "/assets/audio/3c68c0b7.mp3",
  "Question 7. Let's look at the Weather Watch table. Which row has the highest value?": "/assets/audio/21f7c798.mp3",
  "Question 8. Let's look at the Weather Watch table. If we add the values from row 1 and row 2, what is the total?": "/assets/audio/7142c8e.mp3",
  "Question 9. Let's look at the Weather Watch table. If we add the values from row 1 and row 2, what is the total?": "/assets/audio/3c5242b3.mp3",
  "Question 10. Let's look at the Weather Watch table. If we add the values from row 1 and row 2, what is the total?": "/assets/audio/61051d0d.mp3",
  "Question 11. Let's look at the Score Board table. What is the value in row 1 and column 2?": "/assets/audio/27da48b2.mp3",
  "Question 12. Let's look at the Score Board table. What is the value in row 2 and column 2?": "/assets/audio/ff4876e.mp3",
  "Question 13. Let's look at the Score Board table. What is the value in row 3 and column 2?": "/assets/audio/47c3578e.mp3",
  "Question 14. Let's look at the Score Board table. Which row has the highest value?": "/assets/audio/38a812fd.mp3",
  "Question 15. Let's look at the Score Board table. Which row has the highest value?": "/assets/audio/450d3824.mp3",
  "Question 16. Let's look at the Score Board table. Which row has the highest value?": "/assets/audio/3d3d7cbb.mp3",
  "Question 17. Let's look at the Score Board table. Which row has the highest value?": "/assets/audio/4077ce66.mp3",
  "Question 18. Let's look at the Score Board table. If we add the values from row 1 and row 2, what is the total?": "/assets/audio/618dbc0.mp3",
  "Question 19. Let's look at the Score Board table. If we add the values from row 1 and row 2, what is the total?": "/assets/audio/5f242741.mp3",
  "Question 20. Let's look at the Score Board table. If we add the values from row 1 and row 2, what is the total?": "/assets/audio/61ca457.mp3",
  "Question 21. Let's look at the Price Tag Plaza table. What is the value in row 1 and column 2?": "/assets/audio/4f6d0f7a.mp3",
  "Question 22. Let's look at the Price Tag Plaza table. What is the value in row 2 and column 2?": "/assets/audio/526db926.mp3",
  "Question 23. Let's look at the Price Tag Plaza table. What is the value in row 3 and column 2?": "/assets/audio/bb77e3a.mp3",
  "Question 24. Let's look at the Price Tag Plaza table. Which row has the highest value?": "/assets/audio/3a036db5.mp3",
  "Question 25. Let's look at the Price Tag Plaza table. Which row has the highest value?": "/assets/audio/7c1a9b14.mp3",
  "Question 26. Let's look at the Price Tag Plaza table. Which row has the highest value?": "/assets/audio/41ce378d.mp3",
  "Question 27. Let's look at the Price Tag Plaza table. Which row has the highest value?": "/assets/audio/48f5d2.mp3",
  "Question 28. Let's look at the Price Tag Plaza table. If we add the values from row 1 and row 2, what is the total?": "/assets/audio/7eff85f8.mp3",
  "Question 29. Let's look at the Price Tag Plaza table. If we add the values from row 1 and row 2, what is the total?": "/assets/audio/7b77e2f7.mp3",
  "Question 30. Let's look at the Price Tag Plaza table. If we add the values from row 1 and row 2, what is the total?": "/assets/audio/2dcfe0e1.mp3",
  "Question 31. Let's look at the Timetable Trail table. What is the value in row 1 and column 2?": "/assets/audio/47532941.mp3",
  "Question 32. Let's look at the Timetable Trail table. What is the value in row 2 and column 2?": "/assets/audio/5a879f5f.mp3",
  "Question 33. Let's look at the Timetable Trail table. What is the value in row 3 and column 2?": "/assets/audio/39d9801.mp3",
  "Question 34. Let's look at the Timetable Trail table. Which row has the highest value?": "/assets/audio/15806312.mp3",
  "Question 35. Let's look at the Timetable Trail table. Which row has the highest value?": "/assets/audio/2c96ca4d.mp3",
  "Question 36. Let's look at the Timetable Trail table. Which row has the highest value?": "/assets/audio/6eadf7ac.mp3",
  "Question 37. Let's look at the Timetable Trail table. Which row has the highest value?": "/assets/audio/4f3adaf5.mp3",
  "Question 38. Let's look at the Timetable Trail table. If we add the values from row 1 and row 2, what is the total?": "/assets/audio/34071e91.mp3",
  "Question 39. Let's look at the Timetable Trail table. If we add the values from row 1 and row 2, what is the total?": "/assets/audio/307f7b90.mp3",
  "Question 40. Let's look at the Timetable Trail table. If we add the values from row 1 and row 2, what is the total?": "/assets/audio/1d288686.mp3",
  "Question 41. Let's look at the Library Ledger table. What is the value in row 1 and column 2?": "/assets/audio/7b75a941.mp3",
  "Question 42. Let's look at the Library Ledger table. What is the value in row 2 and column 2?": "/assets/audio/7ccced43.mp3",
  "Question 43. Let's look at the Library Ledger table. What is the value in row 3 and column 2?": "/assets/audio/7e243145.mp3",
  "Question 44. Let's look at the Library Ledger table. Which row has the highest value?": "/assets/audio/4efef66a.mp3",
  "Question 45. Let's look at the Library Ledger table. Which row has the highest value?": "/assets/audio/1b50cba9.mp3",
  "Question 46. Let's look at the Library Ledger table. Which row has the highest value?": "/assets/audio/185d5f18.mp3",
  "Question 47. Let's look at the Library Ledger table. Which row has the highest value?": "/assets/audio/4c0b89d9.mp3",
  "Question 48. Let's look at the Library Ledger table. If we add the values from row 1 and row 2, what is the total?": "/assets/audio/224eed3f.mp3",
  "Question 49. Let's look at the Library Ledger table. If we add the values from row 1 and row 2, what is the total?": "/assets/audio/4bb6661e.mp3",
  "Question 50. Let's look at the Library Ledger table. If we add the values from row 1 and row 2, what is the total?": "/assets/audio/256536b8.mp3",
  "Question 51. Let's look at the Fitness Log table. What is the value in row 1 and column 2?": "/assets/audio/7dede486.mp3",
  "Question 52. Let's look at the Fitness Log table. What is the value in row 2 and column 2?": "/assets/audio/4a434b5a.mp3",
  "Question 53. Let's look at the Fitness Log table. What is the value in row 3 and column 2?": "/assets/audio/12747b3a.mp3",
  "Question 54. Let's look at the Fitness Log table. Which row has the highest value?": "/assets/audio/3d307cb.mp3",
  "Question 55. Let's look at the Fitness Log table. Which row has the highest value?": "/assets/audio/7e77ad14.mp3",
  "Question 56. Let's look at the Fitness Log table. Which row has the highest value?": "/assets/audio/c261f3.mp3",
  "Question 57. Let's look at the Fitness Log table. Which row has the highest value?": "/assets/audio/7cf2e92e.mp3",
  "Question 58. Let's look at the Fitness Log table. If we add the values from row 1 and row 2, what is the total?": "/assets/audio/3c5fa188.mp3",
  "Question 59. Let's look at the Fitness Log table. If we add the values from row 1 and row 2, what is the total?": "/assets/audio/6a9512f7.mp3",
  "Question 60. Let's look at the Fitness Log table. If we add the values from row 1 and row 2, what is the total?": "/assets/audio/3c636a1f.mp3",
  "Question 61. Let's look at the Bus Route Book table. What is the value in row 1 and column 2?": "/assets/audio/27f2124f.mp3",
  "Question 62. Let's look at the Bus Route Book table. What is the value in row 2 and column 2?": "/assets/audio/269ace4d.mp3",
  "Question 63. Let's look at the Bus Route Book table. What is the value in row 3 and column 2?": "/assets/audio/25438a4b.mp3",
  "Question 64. Let's look at the Bus Route Book table. Which row has the highest value?": "/assets/audio/236341fa.mp3",
  "Question 65. Let's look at the Bus Route Book table. Which row has the highest value?": "/assets/audio/104ae8c7.mp3",
  "Question 66. Let's look at the Bus Route Book table. Which row has the highest value?": "/assets/audio/43f91388.mp3",
  "Question 67. Let's look at the Bus Route Book table. Which row has the highest value?": "/assets/audio/77a73e49.mp3",
  "Question 68. Let's look at the Bus Route Book table. If we add the values from row 1 and row 2, what is the total?": "/assets/audio/74cacecf.mp3",
  "Question 69. Let's look at the Bus Route Book table. If we add the values from row 1 and row 2, what is the total?": "/assets/audio/61cdb852.mp3",
  "Question 70. Let's look at the Bus Route Book table. If we add the values from row 1 and row 2, what is the total?": "/assets/audio/2d16aad8.mp3",
  "Question 71. Let's look at the Recipe Rack table. What is the value in row 1 and column 2?": "/assets/audio/6cefbe5.mp3",
  "Question 72. Let's look at the Recipe Rack table. What is the value in row 2 and column 2?": "/assets/audio/3e9dcc05.mp3",
  "Question 73. Let's look at the Recipe Rack table. What is the value in row 3 and column 2?": "/assets/audio/766c9c25.mp3",
  "Question 74. Let's look at the Recipe Rack table. Which row has the highest value?": "/assets/audio/54eede94.mp3",
  "Question 75. Let's look at the Recipe Rack table. Which row has the highest value?": "/assets/audio/28c66c8d.mp3",
  "Question 76. Let's look at the Recipe Rack table. Which row has the highest value?": "/assets/audio/59844852.mp3",
  "Question 77. Let's look at the Recipe Rack table. Which row has the highest value?": "/assets/audio/243102cf.mp3",
  "Question 78. Let's look at the Recipe Rack table. If we add the values from row 1 and row 2, what is the total?": "/assets/audio/567cd477.mp3",
  "Question 79. Let's look at the Recipe Rack table. If we add the values from row 1 and row 2, what is the total?": "/assets/audio/28e770a.mp3",
  "Question 80. Let's look at the Recipe Rack table. If we add the values from row 1 and row 2, what is the total?": "/assets/audio/56790be0.mp3",
  "Question 81. Let's look at the Concert Counter table. What is the value in row 1 and column 2?": "/assets/audio/3d64dc7f.mp3",
  "Question 82. Let's look at the Concert Counter table. What is the value in row 2 and column 2?": "/assets/audio/20c05ae1.mp3",
  "Question 83. Let's look at the Concert Counter table. What is the value in row 3 and column 2?": "/assets/audio/7ee59241.mp3",
  "Question 84. Let's look at the Concert Counter table. Which row has the highest value?": "/assets/audio/64869d52.mp3",
  "Question 85. Let's look at the Concert Counter table. Which row has the highest value?": "/assets/audio/226f6ff3.mp3",
  "Question 86. Let's look at the Concert Counter table. Which row has the highest value?": "/assets/audio/1fa7bd6c.mp3",
  "Question 87. Let's look at the Concert Counter table. Which row has the highest value?": "/assets/audio/61beeacb.mp3",
  "Question 88. Let's look at the Concert Counter table. If we add the values from row 1 and row 2, what is the total?": "/assets/audio/6b31f3af.mp3",
  "Question 89. Let's look at the Concert Counter table. If we add the values from row 1 and row 2, what is the total?": "/assets/audio/6eb996b0.mp3",
  "Question 90. Let's look at the Concert Counter table. If we add the values from row 1 and row 2, what is the total?": "/assets/audio/439e673a.mp3",
  "Question 91. Let's look at the Grade Book Grove table. What is the value in row 1 and column 2?": "/assets/audio/61d870ed.mp3",
  "Question 92. Let's look at the Grade Book Grove table. What is the value in row 2 and column 2?": "/assets/audio/5010992b.mp3",
  "Question 93. Let's look at the Grade Book Grove table. What is the value in row 3 and column 2?": "/assets/audio/3e48c169.mp3",
  "Question 94. Let's look at the Grade Book Grove table. Which row has the highest value?": "/assets/audio/46b7dca8.mp3",
  "Question 95. Let's look at the Grade Book Grove table. Which row has the highest value?": "/assets/audio/47865b29.mp3",
  "Question 96. Let's look at the Grade Book Grove table. Which row has the highest value?": "/assets/audio/4854d9aa.mp3",
  "Question 97. Let's look at the Grade Book Grove table. Which row has the highest value?": "/assets/audio/4923582b.mp3",
  "Question 98. Let's look at the Grade Book Grove table. If we add the values from row 1 and row 2, what is the total?": "/assets/audio/1e061c6d.mp3",
  "Question 99. Let's look at the Grade Book Grove table. If we add the values from row 1 and row 2, what is the total?": "/assets/audio/748d2674.mp3",
  "Question 100. Let's look at the Grade Book Grove table. If we add the values from row 1 and row 2, what is the total?": "/assets/audio/334a50cf.mp3"
};
